#!/usr/bin/env php
<?php

use AsyncAws\CodeGenerator\Command\AddChangeLogCommand;
use Symfony\Component\Console\Application;

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "Run `composer install` before you run the `generate` script.\n";
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

$app = new Application('AsyncAws', '0.1.0');
$command = new AddChangeLogCommand();
$app->add($command);
$app->setDefaultCommand($command->getName(), true);

$app->run();
