#!/usr/bin/env php
<?php

use AsyncAws\CodeGenerator\File\Location\AsyncAwsMonoRepoResolver;
use AsyncAws\CodeGenerator\Runner;
use AsyncAws\Core\EnvVar;

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "Run `composer install` before you run the `generate` script.\n";
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

if (null === EnvVar::get('SYMFONY_PATCH_TYPE_DECLARATIONS')) {
    $_SERVER['SYMFONY_PATCH_TYPE_DECLARATIONS'] = 'deprecations=1';
}

Runner::create(
    __DIR__ . '/manifest.json',
    new AsyncAwsMonoRepoResolver(__DIR__ . '/src'),
    __DIR__ . '/.cache/generate'
)->run();
