#!/usr/bin/env php
<?php

require __DIR__.'/vendor/symfony/filesystem/Exception/ExceptionInterface.php';
require __DIR__.'/vendor/symfony/filesystem/Exception/IOExceptionInterface.php';
require __DIR__.'/vendor/symfony/filesystem/Exception/IOException.php';
require __DIR__.'/vendor/symfony/filesystem/Filesystem.php';

use Symfony\Component\Filesystem\Filesystem;

/**
 * Links dependencies to components to a local clone of the main async-aws/aws GitHub repository.
 * Inspired by symfony/symfony/link
 *
 * @author Kévin Dunglas <dunglas@gmail.com>
 */

$copy = false !== $k = array_search('--copy', $argv, true);
$copy && array_splice($argv, $k, 1);
$pathToProject = $argv[1] ?? getcwd();

if (!is_dir("$pathToProject/vendor/async-aws")) {
    echo 'Link (or copy) dependencies to components to a local clone of the main async-aws/aws GitHub repository.'.PHP_EOL.PHP_EOL;
    echo "Usage: $argv[0] /path/to/the/project".PHP_EOL;
    echo '       Use `--copy` to copy dependencies instead of symlink'.PHP_EOL.PHP_EOL;
    echo "The directory \"$pathToProject\" does not exist or the dependencies are not installed, did you forget to run \"composer install\" in your project?".PHP_EOL;
    exit(1);
}

$packages = array();

$filesystem = new Filesystem();
$braces = array('.', 'Integration/*', 'Service');
$directories = array_merge(...array_values(array_map(function ($part) {
    return glob(__DIR__.'/src/'.$part.'/*', GLOB_ONLYDIR | GLOB_NOSORT);
}, $braces)));

foreach ($directories as $dir) {
    if ($filesystem->exists($composer = "$dir/composer.json")) {
        $packages[json_decode(file_get_contents($composer))->name] = $dir;
    }
}

foreach (glob("$pathToProject/vendor/async-aws/*", GLOB_ONLYDIR | GLOB_NOSORT) as $dir) {
    $package = 'async-aws/'.basename($dir);
    if (!$copy && is_link($dir)) {
        echo "\"$package\" is already a symlink, skipping.".PHP_EOL;
        continue;
    }

    if (!isset($packages[$package])) {
        continue;
    }

    $packageDir = ('\\' === DIRECTORY_SEPARATOR || $copy) ? $packages[$package] : $filesystem->makePathRelative($packages[$package], dirname(realpath($dir)));
    $filesystem->remove($dir);

    if ($copy) {
        $filesystem->mirror($packageDir, $dir);
        echo "\"$package\" has been copied from \"$packages[$package]\".".PHP_EOL;
    } else {
        $filesystem->symlink(rtrim($packageDir, '/'), $dir);
        echo "\"$package\" has been linked to \"$packages[$package]\".".PHP_EOL;
    }
}
