<?php

namespace AsyncAws\Iam\ValueObject;

use AsyncAws\Core\Exception\InvalidArgument;
use AsyncAws\Iam\Enum\StatusType;

/**
 * Contains the details of a service-specific credential.
 */
final class ServiceSpecificCredential
{
    /**
     * The date and time, in ISO 8601 date-time format [^1], when the service-specific credential were created.
     *
     * [^1]: http://www.iso.org/iso/iso8601
     */
    private $createDate;

    /**
     * The name of the service associated with the service-specific credential.
     */
    private $serviceName;

    /**
     * The generated user name for the service-specific credential. This value is generated by combining the IAM user's name
     * combined with the ID number of the Amazon Web Services account, as in `jane-at-123456789012`, for example. This value
     * cannot be configured by the user.
     */
    private $serviceUserName;

    /**
     * The generated password for the service-specific credential.
     */
    private $servicePassword;

    /**
     * The unique identifier for the service-specific credential.
     */
    private $serviceSpecificCredentialId;

    /**
     * The name of the IAM user associated with the service-specific credential.
     */
    private $userName;

    /**
     * The status of the service-specific credential. `Active` means that the key is valid for API calls, while `Inactive`
     * means it is not.
     */
    private $status;

    /**
     * @param array{
     *   CreateDate: \DateTimeImmutable,
     *   ServiceName: string,
     *   ServiceUserName: string,
     *   ServicePassword: string,
     *   ServiceSpecificCredentialId: string,
     *   UserName: string,
     *   Status: StatusType::*,
     * } $input
     */
    public function __construct(array $input)
    {
        $this->createDate = $input['CreateDate'] ?? $this->throwException(new InvalidArgument('Missing required field "CreateDate".'));
        $this->serviceName = $input['ServiceName'] ?? $this->throwException(new InvalidArgument('Missing required field "ServiceName".'));
        $this->serviceUserName = $input['ServiceUserName'] ?? $this->throwException(new InvalidArgument('Missing required field "ServiceUserName".'));
        $this->servicePassword = $input['ServicePassword'] ?? $this->throwException(new InvalidArgument('Missing required field "ServicePassword".'));
        $this->serviceSpecificCredentialId = $input['ServiceSpecificCredentialId'] ?? $this->throwException(new InvalidArgument('Missing required field "ServiceSpecificCredentialId".'));
        $this->userName = $input['UserName'] ?? $this->throwException(new InvalidArgument('Missing required field "UserName".'));
        $this->status = $input['Status'] ?? $this->throwException(new InvalidArgument('Missing required field "Status".'));
    }

    /**
     * @param array{
     *   CreateDate: \DateTimeImmutable,
     *   ServiceName: string,
     *   ServiceUserName: string,
     *   ServicePassword: string,
     *   ServiceSpecificCredentialId: string,
     *   UserName: string,
     *   Status: StatusType::*,
     * }|ServiceSpecificCredential $input
     */
    public static function create($input): self
    {
        return $input instanceof self ? $input : new self($input);
    }

    public function getCreateDate(): \DateTimeImmutable
    {
        return $this->createDate;
    }

    public function getServiceName(): string
    {
        return $this->serviceName;
    }

    public function getServicePassword(): string
    {
        return $this->servicePassword;
    }

    public function getServiceSpecificCredentialId(): string
    {
        return $this->serviceSpecificCredentialId;
    }

    public function getServiceUserName(): string
    {
        return $this->serviceUserName;
    }

    /**
     * @return StatusType::*
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    public function getUserName(): string
    {
        return $this->userName;
    }

    /**
     * @return never
     */
    private function throwException(\Throwable $exception)
    {
        throw $exception;
    }
}
