<?php

declare(strict_types=1);

namespace AsyncAws\Core\Credentials;

use AsyncAws\Core\Configuration;
use Symfony\Contracts\Cache\CacheInterface;
use Symfony\Contracts\Cache\ItemInterface;

/**
 * Cache the Credential generated by the decorated CredentialProvider in a persisting pool.
 *
 * The Credential will be reused until it expires.
 *
 * @author Jérémy Derussé <jeremy@derusse.com>
 */
final class PersistingCacheProvider implements CredentialProvider
{
    private const EXPIRATION_DRIFT = 30;

    private $cache;
    private $decorated;

    public function __construct(CredentialProvider $decorated, CacheInterface $cache)
    {
        $this->decorated = $decorated;
        $this->cache = $cache;
    }

    public function getCredentials(Configuration $configuration): ?Credentials
    {
        return $this->cache->get(sha1(\serialize([$configuration, \get_class($this->decorated)])), function (ItemInterface $item) use ($configuration) {
            $credential = $this->decorated->getCredentials($configuration);
            if (null === $credential) {
                $item->expiresAfter(0);
            } elseif (null !== $exp = $credential->getExpireDate()) {
                $item->expiresAt($exp->sub(new \DateInterval(sprintf('PT%dS', self::EXPIRATION_DRIFT))));
            }

            return $credential;
        });
    }
}
