name: Tests

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          ini-values: xdebug.overload_var_dump=1
          tools: prestissimo

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer config minimum-stability dev
          composer req symfony/phpunit-bridge --no-update
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        run: ./vendor/bin/simple-phpunit
