name: Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@1.8.1
      with:
        php-version: 7.4
        coverage: none

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download
      run: |
        curl -L https://github.com/ergebnis/composer-normalize/releases/latest/download/composer-normalize.phar --output normalize.phar
        chmod +x normalize.phar

    - name: Normalize
      run: |
        ./normalize.phar --dry-run

#  roave-bc-check:
#    name: Roave BC Check
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Roave BC Check
#        uses: docker://nyholm/roave-bc-check-ga
