name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@1.8.1
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: prestissimo

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer update --no-interaction --prefer-dist --prefer-stable --optimize-autoloader

      - name: Initialize tests
        run: make initialize

      - name: Run tests
        run: |
          echo ::group::Install
          ./vendor/bin/simple-phpunit install
          echo ::endgroup::
          ./vendor/bin/simple-phpunit
