<?php

namespace AsyncAws\MediaConvert\Enum;

/**
 * Specify the language, using an ISO 639-2 three-letter code in all capital letters. You can find a list of codes at:
 * https://www.loc.gov/standards/iso639-2/php/code_list.php
 */
final class LanguageCode
{
    public const AAR = 'AAR';
    public const ABK = 'ABK';
    public const AFR = 'AFR';
    public const AKA = 'AKA';
    public const AMH = 'AMH';
    public const ARA = 'ARA';
    public const ARG = 'ARG';
    public const ASM = 'ASM';
    public const AVA = 'AVA';
    public const AVE = 'AVE';
    public const AYM = 'AYM';
    public const AZE = 'AZE';
    public const BAK = 'BAK';
    public const BAM = 'BAM';
    public const BEL = 'BEL';
    public const BEN = 'BEN';
    public const BIH = 'BIH';
    public const BIS = 'BIS';
    public const BOD = 'BOD';
    public const BOS = 'BOS';
    public const BRE = 'BRE';
    public const BUL = 'BUL';
    public const CAT = 'CAT';
    public const CES = 'CES';
    public const CHA = 'CHA';
    public const CHE = 'CHE';
    public const CHU = 'CHU';
    public const CHV = 'CHV';
    public const COR = 'COR';
    public const COS = 'COS';
    public const CRE = 'CRE';
    public const CYM = 'CYM';
    public const DAN = 'DAN';
    public const DEU = 'DEU';
    public const DIV = 'DIV';
    public const DZO = 'DZO';
    public const ELL = 'ELL';
    public const ENG = 'ENG';
    public const ENM = 'ENM';
    public const EPO = 'EPO';
    public const EST = 'EST';
    public const EUS = 'EUS';
    public const EWE = 'EWE';
    public const FAO = 'FAO';
    public const FAS = 'FAS';
    public const FIJ = 'FIJ';
    public const FIN = 'FIN';
    public const FRA = 'FRA';
    public const FRM = 'FRM';
    public const FRY = 'FRY';
    public const FUL = 'FUL';
    public const GER = 'GER';
    public const GLA = 'GLA';
    public const GLE = 'GLE';
    public const GLG = 'GLG';
    public const GLV = 'GLV';
    public const GRN = 'GRN';
    public const GUJ = 'GUJ';
    public const HAT = 'HAT';
    public const HAU = 'HAU';
    public const HEB = 'HEB';
    public const HER = 'HER';
    public const HIN = 'HIN';
    public const HMO = 'HMO';
    public const HRV = 'HRV';
    public const HUN = 'HUN';
    public const HYE = 'HYE';
    public const IBO = 'IBO';
    public const IDO = 'IDO';
    public const III = 'III';
    public const IKU = 'IKU';
    public const ILE = 'ILE';
    public const INA = 'INA';
    public const IND = 'IND';
    public const IPK = 'IPK';
    public const ISL = 'ISL';
    public const ITA = 'ITA';
    public const JAV = 'JAV';
    public const JPN = 'JPN';
    public const KAL = 'KAL';
    public const KAN = 'KAN';
    public const KAS = 'KAS';
    public const KAT = 'KAT';
    public const KAU = 'KAU';
    public const KAZ = 'KAZ';
    public const KHM = 'KHM';
    public const KIK = 'KIK';
    public const KIN = 'KIN';
    public const KIR = 'KIR';
    public const KOM = 'KOM';
    public const KON = 'KON';
    public const KOR = 'KOR';
    public const KUA = 'KUA';
    public const KUR = 'KUR';
    public const LAO = 'LAO';
    public const LAT = 'LAT';
    public const LAV = 'LAV';
    public const LIM = 'LIM';
    public const LIN = 'LIN';
    public const LIT = 'LIT';
    public const LTZ = 'LTZ';
    public const LUB = 'LUB';
    public const LUG = 'LUG';
    public const MAH = 'MAH';
    public const MAL = 'MAL';
    public const MAR = 'MAR';
    public const MKD = 'MKD';
    public const MLG = 'MLG';
    public const MLT = 'MLT';
    public const MON = 'MON';
    public const MRI = 'MRI';
    public const MSA = 'MSA';
    public const MYA = 'MYA';
    public const NAU = 'NAU';
    public const NAV = 'NAV';
    public const NBL = 'NBL';
    public const NDE = 'NDE';
    public const NDO = 'NDO';
    public const NEP = 'NEP';
    public const NLD = 'NLD';
    public const NNO = 'NNO';
    public const NOB = 'NOB';
    public const NOR = 'NOR';
    public const NYA = 'NYA';
    public const OCI = 'OCI';
    public const OJI = 'OJI';
    public const ORI = 'ORI';
    public const ORJ = 'ORJ';
    public const ORM = 'ORM';
    public const OSS = 'OSS';
    public const PAN = 'PAN';
    public const PLI = 'PLI';
    public const POL = 'POL';
    public const POR = 'POR';
    public const PUS = 'PUS';
    public const QAA = 'QAA';
    public const QPC = 'QPC';
    public const QUE = 'QUE';
    public const ROH = 'ROH';
    public const RON = 'RON';
    public const RUN = 'RUN';
    public const RUS = 'RUS';
    public const SAG = 'SAG';
    public const SAN = 'SAN';
    public const SIN = 'SIN';
    public const SLK = 'SLK';
    public const SLV = 'SLV';
    public const SME = 'SME';
    public const SMO = 'SMO';
    public const SNA = 'SNA';
    public const SND = 'SND';
    public const SOM = 'SOM';
    public const SOT = 'SOT';
    public const SPA = 'SPA';
    public const SQI = 'SQI';
    public const SRB = 'SRB';
    public const SRD = 'SRD';
    public const SRP = 'SRP';
    public const SSW = 'SSW';
    public const SUN = 'SUN';
    public const SWA = 'SWA';
    public const SWE = 'SWE';
    public const TAH = 'TAH';
    public const TAM = 'TAM';
    public const TAT = 'TAT';
    public const TEL = 'TEL';
    public const TGK = 'TGK';
    public const TGL = 'TGL';
    public const THA = 'THA';
    public const TIR = 'TIR';
    public const TNG = 'TNG';
    public const TON = 'TON';
    public const TSN = 'TSN';
    public const TSO = 'TSO';
    public const TUK = 'TUK';
    public const TUR = 'TUR';
    public const TWI = 'TWI';
    public const UIG = 'UIG';
    public const UKR = 'UKR';
    public const URD = 'URD';
    public const UZB = 'UZB';
    public const VEN = 'VEN';
    public const VIE = 'VIE';
    public const VOL = 'VOL';
    public const WLN = 'WLN';
    public const WOL = 'WOL';
    public const XHO = 'XHO';
    public const YID = 'YID';
    public const YOR = 'YOR';
    public const ZHA = 'ZHA';
    public const ZHO = 'ZHO';
    public const ZUL = 'ZUL';

    public static function exists(string $value): bool
    {
        return isset([
            self::AAR => true,
            self::ABK => true,
            self::AFR => true,
            self::AKA => true,
            self::AMH => true,
            self::ARA => true,
            self::ARG => true,
            self::ASM => true,
            self::AVA => true,
            self::AVE => true,
            self::AYM => true,
            self::AZE => true,
            self::BAK => true,
            self::BAM => true,
            self::BEL => true,
            self::BEN => true,
            self::BIH => true,
            self::BIS => true,
            self::BOD => true,
            self::BOS => true,
            self::BRE => true,
            self::BUL => true,
            self::CAT => true,
            self::CES => true,
            self::CHA => true,
            self::CHE => true,
            self::CHU => true,
            self::CHV => true,
            self::COR => true,
            self::COS => true,
            self::CRE => true,
            self::CYM => true,
            self::DAN => true,
            self::DEU => true,
            self::DIV => true,
            self::DZO => true,
            self::ELL => true,
            self::ENG => true,
            self::ENM => true,
            self::EPO => true,
            self::EST => true,
            self::EUS => true,
            self::EWE => true,
            self::FAO => true,
            self::FAS => true,
            self::FIJ => true,
            self::FIN => true,
            self::FRA => true,
            self::FRM => true,
            self::FRY => true,
            self::FUL => true,
            self::GER => true,
            self::GLA => true,
            self::GLE => true,
            self::GLG => true,
            self::GLV => true,
            self::GRN => true,
            self::GUJ => true,
            self::HAT => true,
            self::HAU => true,
            self::HEB => true,
            self::HER => true,
            self::HIN => true,
            self::HMO => true,
            self::HRV => true,
            self::HUN => true,
            self::HYE => true,
            self::IBO => true,
            self::IDO => true,
            self::III => true,
            self::IKU => true,
            self::ILE => true,
            self::INA => true,
            self::IND => true,
            self::IPK => true,
            self::ISL => true,
            self::ITA => true,
            self::JAV => true,
            self::JPN => true,
            self::KAL => true,
            self::KAN => true,
            self::KAS => true,
            self::KAT => true,
            self::KAU => true,
            self::KAZ => true,
            self::KHM => true,
            self::KIK => true,
            self::KIN => true,
            self::KIR => true,
            self::KOM => true,
            self::KON => true,
            self::KOR => true,
            self::KUA => true,
            self::KUR => true,
            self::LAO => true,
            self::LAT => true,
            self::LAV => true,
            self::LIM => true,
            self::LIN => true,
            self::LIT => true,
            self::LTZ => true,
            self::LUB => true,
            self::LUG => true,
            self::MAH => true,
            self::MAL => true,
            self::MAR => true,
            self::MKD => true,
            self::MLG => true,
            self::MLT => true,
            self::MON => true,
            self::MRI => true,
            self::MSA => true,
            self::MYA => true,
            self::NAU => true,
            self::NAV => true,
            self::NBL => true,
            self::NDE => true,
            self::NDO => true,
            self::NEP => true,
            self::NLD => true,
            self::NNO => true,
            self::NOB => true,
            self::NOR => true,
            self::NYA => true,
            self::OCI => true,
            self::OJI => true,
            self::ORI => true,
            self::ORJ => true,
            self::ORM => true,
            self::OSS => true,
            self::PAN => true,
            self::PLI => true,
            self::POL => true,
            self::POR => true,
            self::PUS => true,
            self::QAA => true,
            self::QPC => true,
            self::QUE => true,
            self::ROH => true,
            self::RON => true,
            self::RUN => true,
            self::RUS => true,
            self::SAG => true,
            self::SAN => true,
            self::SIN => true,
            self::SLK => true,
            self::SLV => true,
            self::SME => true,
            self::SMO => true,
            self::SNA => true,
            self::SND => true,
            self::SOM => true,
            self::SOT => true,
            self::SPA => true,
            self::SQI => true,
            self::SRB => true,
            self::SRD => true,
            self::SRP => true,
            self::SSW => true,
            self::SUN => true,
            self::SWA => true,
            self::SWE => true,
            self::TAH => true,
            self::TAM => true,
            self::TAT => true,
            self::TEL => true,
            self::TGK => true,
            self::TGL => true,
            self::THA => true,
            self::TIR => true,
            self::TNG => true,
            self::TON => true,
            self::TSN => true,
            self::TSO => true,
            self::TUK => true,
            self::TUR => true,
            self::TWI => true,
            self::UIG => true,
            self::UKR => true,
            self::URD => true,
            self::UZB => true,
            self::VEN => true,
            self::VIE => true,
            self::VOL => true,
            self::WLN => true,
            self::WOL => true,
            self::XHO => true,
            self::YID => true,
            self::YOR => true,
            self::ZHA => true,
            self::ZHO => true,
            self::ZUL => true,
        ][$value]);
    }
}
